# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.3
  - 5.4

script: phpunit --configuration .travis_phpunit.xml

before_script:

#services: mongodb

notifications:
#  webhooks: http://requestb.in/1inunuo1

branches:
  only:
    - develop
    - master

